apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tan-dara2643-zip-test-spring
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.telegram: "-1002195638358"
    notifications.argoproj.io/subscribe.on-sync-failed.telegram: "-1002195638358"
    notifications.argoproj.io/subscribe.on-deleted.telegram: "-1002195638358"
    notifications.argoproj.io/subscribe.on-sync-succeeded.updateDeploymentStatusWebhook: ""
    notifications.argoproj.io/subscribe.on-sync-succeeded.gmail: sovannlyna2004@gmail.com
spec:
  project: default
  source:
    repoURL: https://github.com/LynaSovann/tan-dara2643-zip-test-spring.git
    targetRevision: main
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: tan-dara2643-zip-test-spring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 5
