apiVersion: v1
kind: Service
metadata:
  name: tan-dara2643-zip-test-spring-service
spec:
  type: NodePort
  selector:
    app: tan-dara2643-zip-test-spring
  ports:
    - protocol: TCP
      port: 8336
      targetPort: 8080
